/***********************************************************/
/*Author: Rolando Phillips */

/*Purpose: Data Dictionary for INFORMATION_SCHEMA Database/
/*I/O: Varies*/

USE INFORMATION_SCHEMA; /* Command to use the INFORMATION_SCHEMA database*/

SHOW tables; /*Provides a listing of all tables in the database*/

/*There are 59 tables in the database.  The statements below, when executed, 
  describe each field (column), data type, constraint, and default in each table*/
  
DESCRIBE CHARACTER_SETS;
DESCRIBE COLLATIONS;
DESCRIBE COLLATION_CHARACTER_SET_APPLICABILITY;
DESCRIBE COLUMNS;
DESCRIBE COLUMN_PRIVILEGES;
DESCRIBE ENGINES;
DESCRIBE EVENTS;
DESCRIBE FILES;
DESCRIBE GLOBAL_STATUS;
DESCRIBE GLOBAL_VARIABLES;
DESCRIBE KEY_COLUMN_USAGE;
DESCRIBE OPTIMIZER_TRACE;
DESCRIBE PARAMETERS;
DESCRIBE PARTITIONS;
DESCRIBE PLUGINS;
DESCRIBE PROCESSLIST;
DESCRIBE PROFILING;
DESCRIBE REFERENTIAL_CONSTRAINTS;
DESCRIBE ROUTINES;
DESCRIBE SCHEMATA;
DESCRIBE SCHEMA_PRIVILEGES;
DESCRIBE SESSION_STATUS;
DESCRIBE SESSION_VARIABLES;
DESCRIBE STATISTICS;
DESCRIBE TABLES;
DESCRIBE TABLESPACES;
DESCRIBE TABLE_CONSTRAINTS;
DESCRIBE TABLE_PRIVILEGES;
DESCRIBE TRIGGERS;
DESCRIBE USER_PRIVILEGES;
DESCRIBE VIEWS;
DESCRIBE INNODB_LOCKS;
DESCRIBE INNODB_TRX;
DESCRIBE INNODB_SYS_DATAFILES;
DESCRIBE INNODB_LOCK_WAITS;
DESCRIBE INNODB_SYS_TABLESTATS;
DESCRIBE INNODB_CMP;
DESCRIBE INNODB_METRICS;
DESCRIBE INNODB_CMP_RESET;
DESCRIBE INNODB_CMP_PER_INDEX;
DESCRIBE INNODB_CMPMEM_RESET;
DESCRIBE INNODB_FT_DELETED;
DESCRIBE INNODB_BUFFER_PAGE_LRU;
DESCRIBE INNODB_SYS_FOREIGN;
DESCRIBE INNODB_SYS_COLUMNS;
DESCRIBE INNODB_SYS_INDEXES;
DESCRIBE INNODB_FT_DEFAULT_STOPWORD;
DESCRIBE INNODB_SYS_FIELDS;
DESCRIBE INNODB_CMP_PER_INDEX_RESET;
DESCRIBE INNODB_BUFFER_PAGE;
DESCRIBE INNODB_CMPMEM;
DESCRIBE INNODB_FT_INDEX_TABLE;
DESCRIBE INNODB_FT_BEING_DELETED;
DESCRIBE INNODB_SYS_TABLESPACES;
DESCRIBE INNODB_FT_INDEX_CACHE;
DESCRIBE INNODB_SYS_FOREIGN_COLS;
DESCRIBE INNODB_SYS_TABLES;
DESCRIBE INNODB_BUFFER_POOL_STATS;
DESCRIBE INNODB_FT_CONFIG;























































